/* Generated by tools/build-fonts.py. */
StencilFonts.catalog=[
 {
  "id": "blackops",
  "family": "Black Ops One",
  "note": "Askeri stencil, USAAF Stencil’e en yakın açık lisanslı seçenek",
  "bold": false
 },
 {
  "id": "bigshoulders",
  "family": "Big Shoulders Stencil",
  "note": "Dar gotik (grotesk) stencil",
  "bold": true
 },
 {
  "id": "saira",
  "family": "Saira Stencil One",
  "note": "Geniş, modern stencil",
  "bold": false
 },
 {
  "id": "sticknobills",
  "family": "Stick No Bills",
  "note": "Sokak/afiş stencili",
  "bold": true
 },
 {
  "id": "emblema",
  "family": "Emblema One",
  "note": "Kalın, dekoratif stencil",
  "bold": false
 },
 {
  "id": "stardos",
  "family": "Stardos Stencil",
  "note": "Klasik serifli stencil (Ğ, Ş, İ harfleri yok)",
  "bold": true
 }
];
