#!/usr/bin/env python3
"""Builds the embedded stencil fonts in fonts/*.js from Google Fonts sources.

Every font here is licensed under the SIL Open Font License 1.1, which allows
bundling and redistribution. Fonts are subset to Latin + Latin Extended (full
Turkish support where the source has it), variable fonts are pinned to static
instances, and the result is stored as base64 WOFF2 so the app works from
file:// and exported SVGs can embed the font.

Usage: pip install fonttools brotli && python3 tools/build-fonts.py
"""
import base64
import io
import json
import os
import urllib.request

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW = 'https://raw.githubusercontent.com/google/fonts/main/ofl/'
UNICODES = (list(range(0x20, 0x7F)) + list(range(0xA0, 0x250)) + list(range(0x2010, 0x2028))
            + list(range(0x2030, 0x205F)) + [0x20AC, 0x20BA, 0x2122])

# id, family, directory, {css weight: (file, variable axis location or None)}, note
FONTS = [
    ('blackops', 'Black Ops One', 'blackopsone', {400: ('BlackOpsOne-Regular.ttf', None)},
     'Askeri stencil, USAAF Stencil’e en yakın açık lisanslı seçenek'),
    ('bigshoulders', 'Big Shoulders Stencil', 'bigshouldersstencil',
     {400: ('BigShouldersStencil[opsz,wght].ttf', {'wght': 500, 'opsz': 72}),
      700: ('BigShouldersStencil[opsz,wght].ttf', {'wght': 800, 'opsz': 72})},
     'Dar gotik (grotesk) stencil'),
    ('saira', 'Saira Stencil One', 'sairastencilone', {400: ('SairaStencilOne-Regular.ttf', None)},
     'Geniş, modern stencil'),
    ('sticknobills', 'Stick No Bills', 'sticknobills',
     {400: ('StickNoBills[wght].ttf', {'wght': 500}), 700: ('StickNoBills[wght].ttf', {'wght': 800})},
     'Sokak/afiş stencili'),
    ('emblema', 'Emblema One', 'emblemaone', {400: ('EmblemaOne-Regular.ttf', None)},
     'Kalın, dekoratif stencil'),
    ('stardos', 'Stardos Stencil', 'stardosstencil',
     {400: ('StardosStencil-Regular.ttf', None), 700: ('StardosStencil-Bold.ttf', None)},
     'Klasik serifli stencil (Ğ, Ş, İ harfleri yok)'),
]


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def build_face(directory, filename, location):
    font = TTFont(io.BytesIO(fetch(RAW + directory + '/' + urllib.request.quote(filename))))
    if location:
        font = instancer.instantiateVariableFont(font, location)
    opts = subset.Options()
    opts.layout_features = ['kern', 'liga', 'locl', 'mark', 'mkmk', 'ccmp']
    opts.name_IDs = ['*']
    opts.notdef_outline = True
    opts.flavor = 'woff2'
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=UNICODES)
    sub.subset(font)
    chars = ''.join(chr(c) for c in sorted(font.getBestCmap()) if c >= 0x20)
    out = io.BytesIO()
    font.flavor = 'woff2'
    font.save(out)
    return base64.b64encode(out.getvalue()).decode('ascii'), chars


def main():
    os.makedirs(os.path.join(ROOT, 'fonts'), exist_ok=True)
    os.makedirs(os.path.join(ROOT, 'assets', 'licenses'), exist_ok=True)
    catalog = []
    for fid, family, directory, faces, note in FONTS:
        weights, chars = {}, ''
        for weight, (filename, location) in faces.items():
            data, chars = build_face(directory, filename, location)
            weights[str(weight)] = data
        payload = {'family': family, 'format': 'woff2', 'chars': chars, 'weights': weights}
        path = os.path.join(ROOT, 'fonts', fid + '.js')
        with open(path, 'w') as f:
            f.write('/* %s — SIL Open Font License 1.1, see assets/licenses/%s.txt. '
                    'Generated by tools/build-fonts.py. */\n' % (family, fid))
            f.write('StencilFonts.register(%s,%s);\n' % (json.dumps(fid), json.dumps(payload, ensure_ascii=False)))
        with open(os.path.join(ROOT, 'assets', 'licenses', fid + '.txt'), 'wb') as f:
            f.write(fetch(RAW + directory + '/OFL.txt'))
        catalog.append({'id': fid, 'family': family, 'note': note, 'bold': '700' in weights})
        print('%-14s %6d KB  %d chars' % (fid, os.path.getsize(path) // 1024, len(chars)))
    with open(os.path.join(ROOT, 'fonts', 'catalog.js'), 'w') as f:
        f.write('/* Generated by tools/build-fonts.py. */\nStencilFonts.catalog=%s;\n'
                % json.dumps(catalog, ensure_ascii=False, indent=1))


if __name__ == '__main__':
    main()
